name: Issue/PR autoassignment

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: "Autoassign issue/PR"
        if: ${{ !contains(fromJson('["alcuadrado","fvictorio","morgansliman","feuGeneA","kanej"]'), github.event.issue.user.login || github.event.pull_request.user.login) }}
        uses: pozil/auto-assign-issue@cf0dddf9c33ad096975198b22d05870d8016176c
        with:
          assignees: alcuadrado,fvictorio,morgansliman,feuGeneA,kanej
          numOfAssignee: 1
